version: "3.3"
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "33306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./mycustom.cnf:/etc/mysql/conf.di/custom.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD